// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: im.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReq) Reset() {
	*x = SendMessageReq{}
	mi := &file_im_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReq) ProtoMessage() {}

func (x *SendMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReq.ProtoReflect.Descriptor instead.
func (*SendMessageReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SendMessageReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendMessageReq) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageReq) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerMsgId   string                 `protobuf:"bytes,1,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Deduped       bool                   `protobuf:"varint,3,opt,name=deduped,proto3" json:"deduped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResp) Reset() {
	*x = SendMessageResp{}
	mi := &file_im_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResp) ProtoMessage() {}

func (x *SendMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResp.ProtoReflect.Descriptor instead.
func (*SendMessageResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResp) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

func (x *SendMessageResp) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResp) GetDeduped() bool {
	if x != nil {
		return x.Deduped
	}
	return false
}

type AckDeliveryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	ServerMsgId   string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckDeliveryReq) Reset() {
	*x = AckDeliveryReq{}
	mi := &file_im_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckDeliveryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDeliveryReq) ProtoMessage() {}

func (x *AckDeliveryReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDeliveryReq.ProtoReflect.Descriptor instead.
func (*AckDeliveryReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{2}
}

func (x *AckDeliveryReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *AckDeliveryReq) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

type AckDeliveryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckDeliveryResp) Reset() {
	*x = AckDeliveryResp{}
	mi := &file_im_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckDeliveryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckDeliveryResp) ProtoMessage() {}

func (x *AckDeliveryResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckDeliveryResp.ProtoReflect.Descriptor instead.
func (*AckDeliveryResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{3}
}

func (x *AckDeliveryResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type AckReadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	ServerMsgId   string                 `protobuf:"bytes,2,opt,name=server_msg_id,json=serverMsgId,proto3" json:"server_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckReadReq) Reset() {
	*x = AckReadReq{}
	mi := &file_im_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckReadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReadReq) ProtoMessage() {}

func (x *AckReadReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReadReq.ProtoReflect.Descriptor instead.
func (*AckReadReq) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{4}
}

func (x *AckReadReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *AckReadReq) GetServerMsgId() string {
	if x != nil {
		return x.ServerMsgId
	}
	return ""
}

type AckReadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckReadResp) Reset() {
	*x = AckReadResp{}
	mi := &file_im_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckReadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReadResp) ProtoMessage() {}

func (x *AckReadResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReadResp.ProtoReflect.Descriptor instead.
func (*AckReadResp) Descriptor() ([]byte, []int) {
	return file_im_proto_rawDescGZIP(), []int{5}
}

func (x *AckReadResp) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_im_proto protoreflect.FileDescriptor

const file_im_proto_rawDesc = "" +
	"\n" +
	"\bim.proto\x12\x05im.v1\"\x85\x01\n" +
	"\x0eSendMessageReq\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x17\n" +
	"\achat_id\x18\x03 \x01(\tR\x06chatId\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\tR\vclientMsgId\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\"a\n" +
	"\x0fSendMessageResp\x12\"\n" +
	"\rserver_msg_id\x18\x01 \x01(\tR\vserverMsgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\adeduped\x18\x03 \x01(\bR\adeduped\"D\n" +
	"\x0eAckDeliveryReq\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\"\n" +
	"\rserver_msg_id\x18\x02 \x01(\tR\vserverMsgId\"!\n" +
	"\x0fAckDeliveryResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"@\n" +
	"\n" +
	"AckReadReq\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\"\n" +
	"\rserver_msg_id\x18\x02 \x01(\tR\vserverMsgId\"\x1d\n" +
	"\vAckReadResp\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xbc\x01\n" +
	"\fLogicService\x12<\n" +
	"\vSendMessage\x12\x15.im.v1.SendMessageReq\x1a\x16.im.v1.SendMessageResp\x12<\n" +
	"\vAckDelivery\x12\x15.im.v1.AckDeliveryReq\x1a\x16.im.v1.AckDeliveryResp\x120\n" +
	"\aAckRead\x12\x11.im.v1.AckReadReq\x1a\x12.im.v1.AckReadRespB\x13Z\x11tet/src/rpc/pb;pbb\x06proto3"

var (
	file_im_proto_rawDescOnce sync.Once
	file_im_proto_rawDescData []byte
)

func file_im_proto_rawDescGZIP() []byte {
	file_im_proto_rawDescOnce.Do(func() {
		file_im_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)))
	})
	return file_im_proto_rawDescData
}

var file_im_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_im_proto_goTypes = []any{
	(*SendMessageReq)(nil),  // 0: im.v1.SendMessageReq
	(*SendMessageResp)(nil), // 1: im.v1.SendMessageResp
	(*AckDeliveryReq)(nil),  // 2: im.v1.AckDeliveryReq
	(*AckDeliveryResp)(nil), // 3: im.v1.AckDeliveryResp
	(*AckReadReq)(nil),      // 4: im.v1.AckReadReq
	(*AckReadResp)(nil),     // 5: im.v1.AckReadResp
}
var file_im_proto_depIdxs = []int32{
	0, // 0: im.v1.LogicService.SendMessage:input_type -> im.v1.SendMessageReq
	2, // 1: im.v1.LogicService.AckDelivery:input_type -> im.v1.AckDeliveryReq
	4, // 2: im.v1.LogicService.AckRead:input_type -> im.v1.AckReadReq
	1, // 3: im.v1.LogicService.SendMessage:output_type -> im.v1.SendMessageResp
	3, // 4: im.v1.LogicService.AckDelivery:output_type -> im.v1.AckDeliveryResp
	5, // 5: im.v1.LogicService.AckRead:output_type -> im.v1.AckReadResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_im_proto_init() }
func file_im_proto_init() {
	if File_im_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_proto_rawDesc), len(file_im_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_proto_goTypes,
		DependencyIndexes: file_im_proto_depIdxs,
		MessageInfos:      file_im_proto_msgTypes,
	}.Build()
	File_im_proto = out.File
	file_im_proto_goTypes = nil
	file_im_proto_depIdxs = nil
}
