gh label create "week2" --color d87634 --description "Week 2 tasks"
gh label create "week3" --color 5319e7 --description "Week 3 tasks"
gh label create "week4" --color 0a8037 --description "Week 4 tasks"
gh label create "database" --color e99695 --description "Database related"
gh label create "auth" --color f9d0c4 --description "Authentication"
gh label create "config" --color bfdadc --description "Configuration management"
gh label create "websocket" --color fce8cd --description "WebSocket protocol"
gh label create "refactor" --color d4c5f9 --description "Code refactoring"
gh label create "room" --color c2e0c6 --description "Room feature"
gh label create "redis" --color fad8c2 --description "Redis integration"
gh label create "task" --color b39ebf --description "Task layer"
gh label create "api" --color c5def5 --description "API interface"
gh label create "etcd" --color f7d1c6 --description "Service discovery"
gh label create "rpc" --color e6dfb3 --description "RPC communication"
gh label create "frontend" --color d0ede9 --description "Frontend UI"
gh label create "docker" --color c7e0e0 --description "Docker deployment"
gh label create "priority:critical" --color b60205 --description "Critical priority"
gh label create "priority:high" --color d93f0b --description "High priority"